apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 471451201019.dkr.ecr.us-east-1.amazonaws.com/frontend
---

apiVersion: v1
kind: Pod
metadata:
  name: auth-service
spec:
  containers:
    - name: auth-service
      image: 471451201019.dkr.ecr.us-east-1.amazonaws.com/auth-service
      env:
        - name: DB_HOST
          value: "wmp-dev.cite0aq48bao.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "auth_svc_user"
        - name: DB_PASSWORD
          value: "localdev123"
        - name: DB_NAME
          value: "wmp"
        - name: DB_SCHEMA
          value: "auth_schema"
        - name: SERVER_PORT
          value: "8081"
        - name: JWT_SECRET
          value: "myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm"
        - name: PORTFOLIO_SERVICE_URL
          value: "http://localhost:8080"
---

apiVersion: v1
kind: Pod
metadata:
  name: portfolio-service
spec:
  containers:
    - name: portfolio-service
      image: 471451201019.dkr.ecr.us-east-1.amazonaws.com/portfolio-service
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://wmp-dev.cite0aq48bao.us-east-1.rds.amazonaws.com:5432/wmp?currentSchema=portfolio_schema"
        - name: SPRING_DATASOURCE_USERNAME
          value: portfolio_svc_user
        - name: SPRING_DATASOURCE_PASSWORD
          value: localdev123
        - name: JWT_SECRET
          value: myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
        - name: SERVER_PORT
          value: "8080"

---

apiVersion: v1
kind: Pod
metadata:
  name: analytics-service
spec:
  containers:
    - name: analytics-service
      image: 471451201019.dkr.ecr.us-east-1.amazonaws.com/analytics-service
      env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://analytics_svc_user:localdev123@wmp-dev.cite0aq48bao.us-east-1.rds.amazonaws.com:5432/wmp"
        - name: DB_SCHEMA
          value: "analytics_schema"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"

